#!/bin/sh

mkdir -p dst
DST=$(cd dst && pwd)

export C_INCLUDE_PATH="{DST}/usr/include"
export CPLUS_INCLUDE_PATH="${DST}/usr/include"
export LIBRARY_PATH="${DST}/usr/lib"
export PKG_CONFIG_PATH="${DST}/usr/lib/pkgconfig"

meson setup --prefix=/usr audacious-build audacious || exit $?
(cd audacious-build && meson compile) || exit $?
(cd audacious-build && DESTDIR=${DST} meson install) || exit $?

meson setup --prefix=/usr audacious-plugins-build audacious-plugins || exit $?
(cd audacious-plugins-build && meson compile) || exit $?
(cd audacious-plugins-build && DESTDIR=${DST} meson install) || exit $?
