#!/bin/sh

mkdir -p dst
DST=$(cd dst && pwd)

export AUDACIOUS_CFLAGS="-I${DST}/usr/include"
export AUDACIOUS_LIBS="-L${DST}/usr/lib -laudcore"
export PKG_CONFIG_PATH="${DST}/usr/lib/pkgconfig"

export QTCORE_CFLAGS="-DQT_CORE_LIB -I/usr/include/qt6/QtCore -I/usr/include/qt6 -fPIC"
export QTCORE_LIBS="-lQt6Core"
export QT_CFLAGS="-I/usr/include/qt6/QtCore -I/usr/include/qt6 -I/usr/include/qt6/QtGui \
-DQT_WIDGETS_LIB -I/usr/include/qt6/QtWidgets -DQT_GUI_LIB -DQT_CORE_LIB -fPIC"
export QT_LIBS="-lQt6Widgets -lQt6Gui -lQt6Core"
export QT_BINPATH="/usr/lib/qt6/bin"

cd audacious
test -f configure || ./autogen.sh || exit $?
test -f config.h || ./configure --prefix=/usr --enable-gtk || exit $?
make -j4 || exit $?
make -j4 DESTDIR=${DST} install || exit $?

cd ../audacious-plugins
test -f configure || ./autogen.sh || exit $?
test -f config.h || ./configure --prefix=/usr --enable-gtk || exit $?
make -j4 || exit $?
make -j4 DESTDIR=${DST} install
