#!/bin/sh

mkdir -p dst
DST=$(cd dst && pwd)

export AUDACIOUS_CFLAGS="-I${DST}/usr/include"
export AUDACIOUS_LIBS="-L${DST}/usr/lib -laudcore"
export PKG_CONFIG_PATH="${DST}/usr/lib/pkgconfig"

cd audacious
test -f configure || ./autogen.sh || exit $?
test -f config.h || ./configure --prefix=/usr --enable-qt || exit $?
make -j4 || exit $?
make -j4 DESTDIR=${DST} install || exit $?

cd ../audacious-plugins
test -f configure || ./autogen.sh || exit $?
test -f config.h || ./configure --prefix=/usr --enable-qt || exit $?
make -j4 || exit $?
make -j4 DESTDIR=${DST} install
