#!/bin/sh

find -path ./dst -prune -false \
    -o -path '*/meson-private' -prune -false \
    -o -name '*.c' -o -name '*.cc' -o -name '*.h' -o -name Makefile \
    | cut -c3- | sort > audacious.files
